### ISSUE TITLE
Improving DataSource

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/uploads#2]
I Like the way DataSource is a "copy" of the $_FILES superglobals but I don't think I'm alone when stating that using $_FILES abstraction with multiple upload is made more difficult as it should in PHP. Is it possible to borrow How [Aura.Web resolves this](https://github.com/auraphp/Aura.Web/blob/develop-2/src/Request/Files.php#L47) ? It still takes as input the super global but internally it re-arranges the data to facilitate further manipulation. Thought ?

**Comment by codeguy** [comment]
Can you post some example code that demonstrates the new user interface provided by your revised DataSource object compared to the existing implementation?

**Comment by nyamsprod** [comment]
Yes of course, here's [a gist](https://gist.github.com/nyamsprod/30fdb01b963d6abdb854) to explain

**Comment by codeguy** [comment]
Thanks! That helps a bunch. I'll see what I can do to normalize the `$_FILES` input into a similar structure.

**Comment by codeguy** [comment]
This is done
